[build]
  functions = "functions"
  command = "npm install"  
  publish = "public" # or your static folder

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true
  
[functions]
node_bundler = "esbuild"
external_node_modules = ["express"]
